#!/bin/bash -ex
cd $(dirname $0)
source ~/isurc

REPORT_DIR=$(pwd)/report/$(date '+%Y%m%d%H%M%S')
LATEST_DIR=$(pwd)/report/latest
mkdir -p $REPORT_DIR

scp isu1:/var/log/nginx/*.log $REPORT_DIR/
scp isu1:/tmp/*.pprof $REPORT_DIR/
scp isu1:/tmp/bench/* $REPORT_DIR/

python summary_log.py < $REPORT_DIR/access.log > $REPORT_DIR/summary.txt

echo $(pwd)
APP_PATH="webapp/golang/bin/main"
for t in cpu mem block; do
  go tool pprof -svg          $APP_PATH $REPORT_DIR/$t.pprof > $REPORT_DIR/$t.svg
  go tool pprof -text         $APP_PATH $REPORT_DIR/$t.pprof > $REPORT_DIR/$t.txt
  go tool pprof -text -cum    $APP_PATH $REPORT_DIR/$t.pprof > $REPORT_DIR/$t-cum.txt
  go tool pprof -list=main.   $APP_PATH $REPORT_DIR/$t.pprof > $REPORT_DIR/$t.list
  go-torch $APP_PATH $REPORT_DIR/$t.pprof --file=$REPORT_DIR/$t-torch.svg 
done

sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' $REPORT_DIR/pidstat.log > $REPORT_DIR/pidstat.csv
python make_report.py $REPORT_DIR > $REPORT_DIR/index.html
ln -nfs $REPORT_DIR $LATEST_DIR

#sudo mysqldumpslow -t 10 -s t /var/log/mysql/mysql-slow.log > $REPORT_DIR/mysql.txt
