#!/bin/bash +x
SCRIPT_DIR=$(cd $(dirname $0) && pwd)
cd $SCRIPT_DIR

ln -nfs current bench/latest
BENCH_DIR=bench/latest

APP_BIN=work/webapp/golang/app
sudo cat /var/log/nginx/access.log | python $SCRIPT_DIR/summary_log.py > $BENCH_DIR/summary.txt
sudo mysqldumpslow -t 10 -s t /var/log/mysql/mysql-slow.log > $BENCH_DIR/mysql.txt
go tool pprof -seconds 60 -svg $APP_BIN /tmp/cpu.pprof > $BENCH_DIR/cpu.svg
go tool pprof -seconds 60 -svg $APP_BIN /tmp/mem.pprof > $BENCH_DIR/mem.svg
go tool pprof -seconds 60 -svg $APP_BIN /tmp/block.pprof > $BENCH_DIR/block.svg
go tool pprof -seconds 60 -text $APP_BIN /tmp/cpu.pprof > $BENCH_DIR/cpu.txt
go tool pprof -seconds 60 -text $APP_BIN /tmp/mem.pprof > $BENCH_DIR/mem.txt
go tool pprof -seconds 60 -text $APP_BIN /tmp/block.pprof > $BENCH_DIR/block.txt
go tool pprof -seconds 60 -text -cum $APP_BIN /tmp/cpu.pprof > $BENCH_DIR/cpu-cum.txt
go tool pprof -seconds 60 -text -cum $APP_BIN /tmp/mem.pprof > $BENCH_DIR/mem-cum.txt
go tool pprof -seconds 60 -text -cum $APP_BIN /tmp/block.pprof > $BENCH_DIR/block-cum.txt
go tool pprof -seconds 60 -list=main. $APP_BIN /tmp/cpu.pprof > $BENCH_DIR/cpu.list
go tool pprof -seconds 60 -list=main. $APP_BIN /tmp/mem.pprof > $BENCH_DIR/mem.list
go tool pprof -seconds 60 -list=main. $APP_BIN /tmp/block.pprof > $BENCH_DIR/block.list
go-torch $APP_BIN /tmp/cpu.pprof --seconds 60 --file=$BENCH_DIR/cpu-torch.svg
go-torch $APP_BIN /tmp/mem.pprof --seconds 60 --file=$BENCH_DIR/mem-torch.svg
go-torch $APP_BIN /tmp/block.pprof --seconds 60 --file=$BENCH_DIR/block-torch.svg
cat $BENCH_DIR/pidstat.log | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//g;s/[ ]\+/,/g' > $BENCH_DIR/pidstat.csv

python $SCRIPT_DIR/make_report.py $BENCH_DIR > $BENCH_DIR/index.html
