#!/bin/bash +x
SCRIPT_DIR=$(cd $(dirname $0) && pwd)
cd $SCRIPT_DIR

timestamp=$(date '+%Y%m%d%H%M%S')
BENCH_DIR=bench/$timestamp
mkdir -p $BENCH_DIR

ln -nfs $timestamp bench/current
(timeout 60 dstat -tam --output=$BENCH_DIR/dstat.csv >/dev/null 2>&1 &)
(timeout 60 pidstat -C 'nginx|mysql|app' -hur -p ALL 1 > $BENCH_DIR/pidstat.log &)
(timeout 60 myprofiler -user root > $BENCH_DIR/myprofiler.log &)
(timeout 60 netstat -a --tcp -c > $BENCH_DIR/netstat.log &)

