#!/bin/bash
SCRIPT_DIR=$(cd $(dirname $0) && pwd)
cd $SCRIPT_DIR

rm /tmp/cpu.pprof 
rm /tmp/mem.pprof
rm /tmp/block.pprof

sudo truncate -s0 /var/log/nginx/access.log 
sudo truncate -s0 /var/log/mysql/mysql-slow.log

sudo systemctl daemon-reload
sudo systemctl restart mysql
sudo systemctl restart nginx
sudo systemctl restart isu-go

mysql -u root -e 'set global slow_query_log_file = "/var/log/mysql/mysql-slow.log";'
mysql -u root -e 'set global long_query_time = 0;'
mysql -u root -e 'set global slow_query_log = ON;'

